### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by msurguy** [mate-h/supershapes#1]
Hello and thanks for making this! I make lots of SVG tools available on DrawingBots.net and looking at using this package.

This package is missing license info, could you please add it in the repo?

Thank you!

**Comment by mate-h** [comment]
Hello, thanks for reaching out! Sure thing, I will add the MIT licence.

**Comment by mate-h** [comment]
Any contributions back to the repo are welcome!

**Comment by msurguy** [comment]
Thank you @mate-h ! 

I might create a PR to specify rounding per-point, but I need some help understanding about rounding clamping. I see that index.js and main.js have different logic for rounding and wanted to know which one is right? 

In the main.js there's clamping done to get minimum of rounding and half segment length:

https://github.com/mate-h/supershape/blob/master/src/main.js#L246

In index.js this is absent. Would be great to know what should happen when the rounding value is greater than half or even whole segment length.

**Comment by mate-h** [comment]
Hi! I just remembered that you posted a comment here. I have opened a new issue for the ideas you raised. I will start looking into it now and see what I find.

#2

**Comment by msurguy** [comment]
Thank you @mate-h !
